### ISSUE TITLE
Streamline in Involvement Map

### ISSUE THREAD

**Issue by giulioberna** [Mensen/swa-matlab#1]
This would be nice

**Comment by Mensen** [comment]
Basically, changing this would involve changing the plotting function used from `ept_topoplot.m` to `swa_DelayPlot.m`, which I wanted to do anyways to avoid the different size topography maps for the delay and the involvement

**Comment by Mensen** [comment]
This was done in 50a974d974147afae16d2e01a177958b9faac59d and e1b1094a7b884a01c122b96dbf97b78bf18e76b7

Now the [swa_DelayPlot.m](https://github.com/Mensen/swa-matlab/blob/50a974d974147afae16d2e01a177958b9faac59d/Dependencies/swa_DelayPlot.m) is always called to plot both the delay map and the involvement map and if no map was calculated during the call to [FindSTTravelling.m](https://github.com/Mensen/swa-matlab/blob/50a974d974147afae16d2e01a177958b9faac59d/ST/swa_FindSTTravelling.m) then one is made on the spot

Let me know if I can close this...
