### ISSUE TITLE
add the option 'use scoring from wispic'

### ISSUE THREAD

**Issue by AnnaCastelnovo** [Mensen/swa-matlab#13]
Particularly useful if you want people from wispic to use your toolbox to analyse their old databases without rescoring them all.

I'm not able, and I don't want to change your code, but I wrote this (please don't laugh, I know it's not well written, and I will be happy if you also improve these few lines): could you please add the option as suggested in comments?

%% Convert_WISPICscorings_To_Armand_Toolbox
%% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% load the set file you want to stage
EEG = pop_loadset();
EEG = pop_saveset(EEG); % save it with another name to avoid to overwrite the previous scoring. this point has to be changed. better to add the option inside the toolbox so you have two scoring files and you have the option to choose one of the two. don't want to change anything in the toolbox on my own.
% load the WISC scoring variable
[fileName, filePath] = uigetfile('_.mat'); %find the big WISC .mat file
load ([filePath fileName], 'sesscoringinfoss'); %load the staging variable only
% save it if you want
save ('scoring_WISPIC.mat', 'sesscoringinfoss', '-v7.3');
% convert from WSIC 6sec_srate128 to Armand samplepoints 
scoring_WISPIC_converted = zeros(1,length(EEG.data));
onset = round (sesscoringinfoss (1,1) \* EEG.srate/128)
offset = size(sesscoringinfoss,1) \* 6_200 + round (sesscoringinfoss (1,1) \* EG.srate/128)-1
scoring_WISPIC_converted (onset:offset) = [reshape(repmat(sesscoringinfoss(:,3), 1, 6_EEG.srate)', 1 , size(sesscoringinfoss,1)_6_EEG.srate)]; 
% WISC stage number ---> Armand stage number 
scoring_WISPIC_converted = chagem(scoring_WISPIC_converted, [1 2 3 5], [-1 -2 -3 1]);
% save it if you want
save ('scoring_WISPIC_for_ArmandToolbox.mat', 'scoring_WISPIC_converted', '-v7.3') 
% save the new filed into the Armand big EEG variable of the new set file
% (as previously said this point has to be changed)
EEG.swa_scoring.stages = scoring_WISPIC_converted_onset_offset

**Comment by Mensen** [comment]
This is too specific to be included in the general version of the toolbox... but its good to know that you have these scripts working for you for other people in the lab that might have used the WISPIC scoring in the past.
