### ISSUE TITLE
differentiated markinings

### ISSUE THREAD

**Issue by AnnaCastelnovo** [Mensen/swa-matlab#22]
Hi Armand, I'm trying to find a smarter  way to mark arousals. Your swa_SleepScoring toolbox could be really useful, because it allows me to mark them with an extremely high temporal precision (Alice is not that precise, I discovered). The problem is that I would like to differentiate classical arousals (according to the definition by AASM) from hypersynchronous high voltage delta waves with increased EMG, that are sometimes considered 'arousal reactions'. So I would like to create two different 'pools' or 'sets' of arousals, is it this easy and quick to change for you?

**Comment by Mensen** [comment]
Hey! I've been thinking about implementing something like an option menu for event markings for quite some time to do just like you describe but haven't gotten around to that yet. I'll have a look at the current code I have and see how long it would take me to implement something like that, but I'm not sure what the best way would be. I'll get back to you on that one, but it probably won't happen too soon.

**Comment by AnnaCastelnovo** [comment]
Ok, thanks Armand

**Comment by Mensen** [comment]
Since all sleep scoring procedures have now been further developed in [csc-eeg-tools](https://github.com/CSC-UW/csc-eeg-tools), there are various solutions to this problem in that toolbox.
