### ISSUE TITLE
angle plots visualization

### ISSUE THREAD

**Issue by AnnaCastelnovo** [Mensen/swa-matlab#26]
I had problems in the  angle plots visualization with all matlab versions (from 2010 to 2015). 
I used the fill function instead of the patch and it seems working nicely.

set(gca, 'nextplot', 'add');
h.plt = polar(tout, rout);
[xout, yout] = pol2cart(tout, rout_mean_pt);
set(gca, 'nextplot', 'add');
fill(xout, yout, 'r');

**Comment by Mensen** [comment]
Yes, I started finding the odd triangles after 2014b, but possibly I didn't really notice that much before.

In the most recent release, I just stopped filling the plots altogether and I actually like the resulting look... but if fill works for you then that's great and easily changeable.

**Comment by AnnaCastelnovo** [comment]
Uh, I thought I had the same problem w 2010, but it's possible I do not
remember well.
I found filling/patches useful for in-between-groups comparisons, but yep,
I personally like rose plots wo patches for single subjects.

2015-06-09 6:38 GMT-05:00 Armand Mensen notifications@github.com:
