### ISSUE TITLE
compare origins

### ISSUE THREAD

**Issue by AnnaCastelnovo** [Mensen/swa-matlab#39]
Hi Armand,

In SW variable, origins are saved as x and y of a 40*40 grid. So I created a grid and referred each origin to a specific cell of the 1600 I created and than compared origins between groups. I was wandering maybe was better to go back to the channel structure at a certain point. What do you advise?

Thanks,

Anna

**Comment by Mensen** [comment]
Hi Anna,

I would not use the delay map for any specific purpose. They are there to pass on to the travelling scripts and easily plot in the explorer.

The origin information you are looking for is in the `SW.Travelling_Delays` field of the structure. This gives the delay at the channel level. Then to determine the origin you can look for channels with a low delay (e.g. < 2 samples).

I definitely advise going to the channel level and not some interpolated map for any analysis of delays.

Good luck!
