### ISSUE TITLE
Add/Remove Wave Option

### ISSUE THREAD

**Issue by giulioberna** [Mensen/swa-matlab#4]
Apparently, it is possible to remove a wave (using the X button) but it would be nice to have the possibility to add it back in case you have a second thought. Also, it would be great to have the possibility of adding a wave by clicking on a specific window in the EEG signal (but not particularly relevant if we can improve the automated detection a bit)...

**Comment by Mensen** [comment]
Hmmm... I can imagine an undelete function for the last deleted wave...

Not sure how to implement that exactly, but would be possible.

The addition of a wave will be harder and I'll open up a separate issue for that.

**Comment by giulioberna** [comment]
Well I think the possibility to re-add the last removed wave would be enough. It is simply useful in case one removes a wave unintentionally.

It should be possible to save a variable containing a copy of the ST structure each time you remove a wave. Then you can just re-load this backup copy if you decide to undo the wave removal.

**Comment by Mensen** [comment]
Now you can simply add a wave back that you might have accidentally deleted through the same process as adding any other wave as of 89721321c51b4e663babf4755f3419094df437d0
