### ISSUE TITLE
swa_SleepScoring & matlab verisons

### ISSUE THREAD

**Issue by AnnaCastelnovo** [Mensen/swa-matlab#41]
Hi Armand,

I tried to use your scoring tool with matlab 2014a and everything works smoothly.

I tried to use your scoring tool with matlab 2015a and I have this error:
Struct contents reference from a non-struct array object.
Error in swa_SleepScoring>menu_LoadEEG (line 256)
set(handles.StatusBar, 'String', 'Busy: Loading EEG (May take some time)...');
drawnow;
Error while evaluating Menu Callback

I tried to use your scoring tool with matlab 2016a and I have this error:
Undefined function 'setVerticalAlignment' for input arguments of type 'handle.handle'.
Error in swa_SleepScoring>DefineInterface (line 100)
jStatusBar.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
Error in swa_SleepScoring (line 8)
DefineInterface

**Comment by Mensen** [comment]
Just to be sure. Is this with the newest version of the toolbox in the develop branch?

I thought I took care of the second issue, but it used to be that you just had to close the window and try again. Not sure what is happening with 2015a, I was using 2015b this morning and scoring with no problems.

I'll try and reproduce the error and get back to you.

**Comment by stede** [comment]
Hi Armand,
I have a similar problem with ML 14b (maci64):
#######
Undefined function 'findjobj' for input arguments of type
'matlab.ui.control.UIControl'.

Error in swa_SleepScoring>DefineInterface (line 98)
jStatusBar = findjobj(handles.StatusBar);

Error in swa_SleepScoring (line 8)
DefineInterface

Attempt to reference field of non-structure array.

Error in swa_SleepScoring>menu_LoadEEG (line 273)
set(handles.StatusBar, 'String', 'Busy: Loading EEG (May take some
time)...'); drawnow;

Error while evaluating Menu Callback

#####

Any idea how this could be fixed?
Thanks,
stefan

**Comment by Mensen** [comment]
Hi Stefan!

It seems it can't find the function `findjobj` which is part of the undocumented Matlab toolbox which is supplied also in the dependencies folder. Did you make sure to add all folders **& subfolders** of the toolbox to the matlab path before running the `swa_SleepScoring` ?

Otherwise, what is the output when you type `which findjobj`

It should be something like `...swa-matlab/Dependencies/UndocumentedMatlab/findjobj.m`

**Comment by Mensen** [comment]
All sleep scoring is now developed in [csc-eeg-tools](https://github.com/CSC-UW/csc-eeg-tools)
