### ISSUE TITLE
Channel location file

### ISSUE THREAD

**Issue by sfattinger** [Mensen/swa-matlab#45]
Hi Armand
When you were in Zurich, you gave me the snf_egi_125.xyz file. I am now looking for an electrode location file with all 128 (or 129, including Cz) electrodes. But so far I cannot find a file containing the same coordinates as in your snf_egi_125.xyz file. Could you please send me the original file (without the electrode numbers 49, 56 107 and 113 deleted).
Thank you very much.
Best 
Sara

**Comment by Mensen** [comment]
The coordinates do not to be the exact same and you can basically use any coordinate system that is supported by EEGLAB, which is basically every one I have ever seen. EEGLAB has the locations for the EGI nets in their "sample_locs" folder.

If you don't have your own file, or don't have the EEGLAB one I can send it to you.
