### ISSUE TITLE
Individual Wave Plot - Options

### ISSUE THREAD

**Issue by giulioberna** [Mensen/swa-matlab#8]
Minor suggestion:

Sometimes waves are too large for the plot scale. It would be nice to have an 'auto-scale' option, so that amplitude (Y) scale change according to wave dimension.

Also, sometimes the green and blue waves are confusing. It would be nice to be able to deactivate one or both of them.

**Comment by Mensen** [comment]
Good ideas!

**Comment by Mensen** [comment]
Autoscale was addressed in commit 5536e09c9dd5c59ea242dc76b97038d856251a7c

Theta and alpha checkboxes added in 1ae6568197af8718e7fae08f5ea4c7f7b74ad392

Let me know if I can close this now...
